development:
  adapter: postgresql
  encoding: unicode
  database: lyl_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lyl_test
  pool: 5
  username:
  password:
